version: "3.9"

services:
  db:
    image: postgres:16
    container_name: games_db
    environment:
      POSTGRES_USER: games_user
      POSTGRES_PASSWORD: games_pass
      POSTGRES_DB: games_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: games_api
    ports:
      - "24531:24531"
    environment:
      PORT: 24531
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: games_user
      DB_PASSWORD: games_pass
      DB_NAME: games_db
    depends_on:
      - db

volumes:
  postgres_data: